# https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup
liquor_sales: # dbt_demo name. This is where dbt looks for from dbt_project.yml -> find the named profile here. Can also be overwritten by dbt run --profiles. See dbt run --help for more info
  target: jaffle_sql # default target for profile, points to 1 of the output below # define target in dbt CLI via --target
  outputs:
    threads: 1
    location: US
    priority: interactive
    jaffle_sql:
      type: bigquery
      method: oauth
      project: "sctp-dsai-ds2" # GCP project id
      dataset: "liquor_demo"
      retries: 2
  config:
    send_anonymous_usage_stats: False